
@baseUrl = http://localhost:3000

### Create Specialty - Hematology
POST {{baseUrl}}/specialties
Content-Type: application/json

{
  "name": "Hematology"
}

### Create Specialty - Microbiology
POST {{baseUrl}}/specialties
Content-Type: application/json

{
  "name": "Microbiology"
}

### List Specialties
GET {{baseUrl}}/specialties

### Create Staff
POST {{baseUrl}}/staff
Content-Type: application/json

{
  "firstName": "Asha",
  "lastName": "Kulkarni",
  "email": "asha.kulkarni@example.com",
  "phoneNumber": "9999999999",
  "addressLine1": "123, FC Road",
  "city": "Pune",
  "countryState": "Maharashtra",
  "country": "India",
  "postalCode": "411005",
  "specialtyIds": [1, 2]
}

### List Staff
GET {{baseUrl}}/staff

### Remove Staff Specialty
DELETE {{baseUrl}}/staff/1/specialties/2

### Delete Staff
DELETE {{baseUrl}}/staff/1
